site_name: Dasharo Open Source Firmware vPub (aka 3mdeb vPub)
site_url: https://vpub.dasharo.com/
theme:
    name: material
    favicon: images/favicon.png
    logo: images/dasharo-logo.png
extra_css:
    - stylesheets/extra.css
google_analytics:
    - UA-39420295-13
    - auto
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
    - attr_list
