site_name: Dasharo Open Source Firmware vPub (aka 3mdeb vPub)
site_url: https://vpub.dasharo.com/
theme:
    name: material
    favicon: images/favicon.png
    logo: images/dasharo-logo.png
extra:
    social:
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/dasharo_com
          name: Dasharo on Twitter
copyright: Sponsored by <a href="https://docs.dasharo.com"><i>Dasharo</i></a>
extra_css:
    - stylesheets/extra.css
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
    - attr_list
    - meta
    - tables
    - pymdownx.tasklist:
          custom_checkbox: true
plugins: []
